
import React from 'react';
import { AuthProvider } from '@/context/auth.context';
import { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={inter.className} suppressHydrationWarning={true}>
          <div>
            <Navbar />
          </div>

          <div>{children}</div>
        </body>
      </html>
    </AuthProvider>
  );
}
